# Date: 05/12/2021
# Author: fedeoli
# Info: Centos with wincc oa installation and gui setup

# from CentOS distro
FROM centos-wincc-preints

# set default shell
SHELL ["/bin/bash","-c"]

### INSTALL BASE STUFF ###
# install sudo
RUN yum install -y sudo

# install gedit
RUN yum install -y gedit

# Install TMUX
RUN yum install -y tmux

# Install unzip
RUN yum install -y unzip

# install passwd
RUN yum install -y passwd

###### MANAGE USERS ######
# change root password
RUN echo root | passwd --stdin root 

# create wincc user
RUN useradd -m wincc

# set user password to wincc
ARG user=wincc
RUN echo $user | passwd --stdin wincc

# add to wheel
RUN usermod -aG wheel wincc

# run useless sudo from wincc (avoid first usage message)
RUN echo wincc | sudo -S echo ciao >> ciao.txt
RUN rm ciao.txt

### WINCC OA INSTALLATION ###
# create installation directory
RUN mkdir /home/wincc/installation
RUN mv /media/wincc_installation/winccOA_linux.zip /home/wincc/installation/
WORKDIR /home/wincc/installation
RUN unzip winccOA_linux.zip -d ./winccOA_linux
WORKDIR /home/wincc/installation/winccOA_linux

# import keys
RUN rpm --import public.key
RUN rpm --import vimaccoa.key

# install wincc oa
RUN yum install -y *.rpm

# add extra repository
RUN yum install -y epel-release 

# add permissions to wincc
RUN chown -R wincc /etc/opt/pvss
RUN chmod -R 755 /etc/opt/pvss

# create project directory
RUN mkdir /opt/WinCC_OA/3.17/projects/
RUN chown -R wincc /opt/WinCC_OA/3.17/projects/
RUN chmod -R 755 /opt/WinCC_OA/3.17/projects/


### USING WINCC USER ###
# set wincc as default user
USER wincc

# set wincc home as working directory
WORKDIR /home/wincc

